version: '3.3'

services:
  postgres:
    container_name: cardgame_db
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - 5432:5432
    volumes:
      - ./init-data/init-postgres-db.sh:/docker-entrypoint-initdb.d/initdb.sh
      - pgdata:/DATA
volumes:
  pgdata:
